FROM mysql:5.7

ENV MYSQL_DATABASE=test \
    MYSQL_ROOT_PASSWORD=password \
    MYSQL_USER=test \
    MYSQL_PASSWORD=password

COPY ./db_scripts/mysql/init_db.sql /docker-entrypoint-initdb.d/init_db.sql